# Generated by Django 4.1.1 on 2022-10-01 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CoffeeBaseApp', '0003_bookinstance_borrower'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookinstance',
            options={'ordering': ['due_back'], 'permissions': (('can_mark_returned', 'Set book as returned'),)},
        ),
    ]
